Add tech spec template to discussion
timmyichen/dev-directory pull request #18
Opened 2023-03-11 00:18 UTC by Caleb-Cohen

# Description

Should add a tech spec template, but idk. 

## Testing

Describe what a reviewer should do to test your code, including instructions for manually testing as well as relevant automated test suites to run.

## Type of change

Please select everything applicable.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires an update to testin

# Checklist:

- [ ] Changes have new/updated automated tests
- [ ] Changes have been manually tested
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

2023-03-11 01:20 UTC, timmyichen approved these changes
🎉

2023-03-11 02:12 UTC, timmyichen requested changes
Oops - actually I think we need to change the label here

2023-03-11 02:12 UTC, timmyichen commented on .github/DISCUSSION_TEMPLATE/technical-specification.md
> +labels: tech spec
I think this needs to be `technical-specification-review` instead

2023-03-11 13:42 UTC, Caleb-Cohen commented
Hello everyone, good morning.

2023-03-11 13:58 UTC, devonzara commented on .github/DISCUSSION_TEMPLATE/technical-specification.md
> +**Delete the text above before submitting**
Perhaps this should read "**Delete this and the text above before submitting.**"...

2023-03-11 13:59 UTC, devonzara commented on .github/DISCUSSION_TEMPLATE/technical-specification.md
> +## Data model:
How nit-picky are we wanting to be with reviews? 🤔

Capitalize "Model"?

2023-03-11 19:34 UTC, timmyichen approved these changes
TY for making the change! Approval from me but I'll defer to the others re the other comments

2023-03-11 22:25 UTC, MatthewBozin approved these changes

2023-03-12 19:21 UTC, Caleb-Cohen commented
> TY for making the change! Approval from me but I'll defer to the others re the other comments

I'm actually not sure this works. I tested it out at Together and didn't seem to do anything.

2023-03-12 23:22 UTC, timmyichen commented
> I'm actually not sure this works. I tested it out at Together and didn't seem to do anything.

Just looked into it, looks like the template is different - YAML, not markdown, but allows for greater customization: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

2023-03-13 17:25 UTC, MainlyColors commented
> > I'm actually not sure this works. I tested it out at Together and didn't seem to do anything.
> 
> Just looked into it, looks like the template is different - YAML, not markdown, but allows for greater customization: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

So does this need to be converted to YAML because the linked article mentions Markdown is still possible?

> You can use both Markdown and YAML issue templates in your repository. If you want to convert a Markdown issue template to a YAML issue form template - Linked Article

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#converting-a-markdown-issue-template-to-a-yaml-issue-form-template

2023-03-13 17:28 UTC, timmyichen commented
> So does this need to be converted to YAML because the linked article mentions Markdown is still possible?

Caleb got something working in a test repo, he'll have updates here soon I think!

2023-03-13 18:28 UTC, Caleb-Cohen commented
> > So does this need to be converted to YAML because the linked article mentions Markdown is still possible?
> 
> Caleb got something working in a test repo, he'll have updates here soon I think!

done

2023-03-13 18:30 UTC, timmyichen commented
> done, looks pretty dank

Share a screenshot! We as reviewers have no way of verifying what it looks like 🙃

2023-03-13 18:45 UTC, Caleb-Cohen commented
> > done, looks pretty dank
> 
> Share a screenshot! We as reviewers have no way of verifying what it looks like 🙃

Dank is a objective and testable fact, why require a photo? It's dank regardless. 

<img width="790" alt="Screenshot 2023-03-13 at 1 45 06 PM" src="https://user-images.githubusercontent.com/75268174/224799737-86a7d073-6529-4bbf-9669-9d5218fadb01.png">

2023-03-13 18:54 UTC, devonzara approved these changes
Looks good!

2023-03-13 19:04 UTC, timmyichen approved these changes
dank levels are off the charts

2023-03-13 19:09 UTC, code2244 approved these changes
so dank!

2023-03-14 17:17 UTC, merged

2023-03-14 17:17 UTC, Caleb-Cohen commented
LET THERE BE DISCUSSION TEMPLATES