#8 change user model
timmyichen/dev-directory pull request #24
Opened 2023-03-11 04:14 UTC by MatthewBozin

Closes #8 

# Description

Added new fields to user model.
Performed migration for model changes.
Updated auth/user code with Discord username field.
Updated acceptance tests with Discord username field.

## Testing

Describe what a reviewer should do to test your code, including instructions for manually testing as well as relevant automated test suites to run.

Automated: `npm run test:server`
Manual: go through app auth flow

## Type of change

Please select everything applicable.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires an update to testing

# Checklist:

- [x] Changes have new/updated automated tests
- [x] Changes have been manually tested
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2023-03-11 07:03 UTC, timmyichen requested changes
Great work! I just have some small comments but otherwise it looks good!

2023-03-11 07:03 UTC, timmyichen commented on server/lib/auth.ts
> +    discord_name: user.username,
So this just saves the username, but doesn't save the discriminator.  When I console.log the user here and log in, I see:
```
{                                              
  id: '437048770237169666',                    
  username: 'chimten',                         
  display_name: null,                          
  avatar: '450a0b622a7c905c4c75e190cb21f2df',  
  avatar_decoration: null,                     
  discriminator: '3819',                       
```

So we want to construct the `discord_name` in the format of `username#discriminator`

2023-03-11 19:57 UTC, MatthewBozin commented
Thanks for the responses @timmyichen, it's always good to follow convent8ion! I've made the requested changes!

2023-03-11 20:09 UTC, timmyichen approved these changes
LGTM!

2023-03-11 21:48 UTC, wo1vin approved these changes
What he said.

2023-03-12 00:46 UTC, MainlyColors commented on server/lib/auth.ts
> +  console.log(user);
Do you want to leave this rogue console.log here?

2023-03-12 00:47 UTC, MainlyColors commented on server/lib/auth.ts
> +  console.log(user);
nvm, saw it was removed

2023-03-12 00:48 UTC, MainlyColors approved these changes
LGTM

2023-03-12 00:52 UTC, merged